apiVersion: v1
kind: Pod
metadata:
  name: islab-db
  labels:
    app: islab-db
spec:
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
  containers:
    - name: maria-db
      image: mariadb:10.7.1
      resources:
        requests:
          memory: "512M"
          cpu: "250m"
      ports:
        - containerPort: 3306
      env:
        - name: MARIADB_ROOT_PASSWORD
          value: password
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: db-volume
  volumes:
    - name: db-volume
      hostPath:
        path: /mnt/k8s-data/islab-db
        type: DirectoryOrCreate
