apiVersion: v1
kind: Service
type:
metadata:
  labels:
    name: islab-httpd
  name: islab-httpd
spec:
  selector:
    app: islab-httpd
  type: NodePort
  ports:
    - port: 80
      nodePort: 30446
      targetPort: 80
      protocol: TCP
