apiVersion: v1
kind: Service
metadata:
  name: islab-k8s-service
  namespace: kube-system
spec:
  type: NodePort
  selector:
    app: islab-k8s-master
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30445
