apiVersion: apps/v1
kind: Deployment
metadata:
  name: islab-k8s-master
  namespace: kube-system
  labels:
    app: islab-k8s-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: islab-k8s-master
  template:
    metadata:
      labels:
        app: islab-k8s-master
    spec:
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      serviceAccountName: islab-k8s
      containers:
        - name: islab-k8s-master
          image: yogawulala/k8s-api-server-master:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "500m"
              memory: "1024M"
          command: ["/bin/bash"]
          args: ["-c", "/app/main"]
          env:
            - name: LISTEN_IP
              value: "0.0.0.0"
            - name: LISTEN_PORT
              value: "8080"
            - name: DEVELOPE
              value: "false"
            - name: DEBUG
              value: "false"
            - name: LOG_LEVEL
              value: "INFO"
            - name: GPU_WEEKS
              value: "0"
            - name: GPU_DAYS
              value: "0"
            - name: GPU_HOURS
              value: "3"
            - name: GPU_MINUTES
              value: "0"
            - name: GPU_SECONDS
              value: "0"
          volumeMounts:
            - name: log-dir
              mountPath: /app/log
            - name: deploy-dir
              mountPath: /app/deploy
            - name: data-dir
              mountPath: /app/data
            - name: kube-config
              mountPath: /root/.kube/config
      volumes:
        - name: log-dir
          hostPath:
            type: DirectoryOrCreate
            path: /etc/islab-k8s/backend/log
        - name: deploy-dir
          hostPath:
            type: Directory
            path: /etc/islab-k8s/backend/deploy
        - name: data-dir
          hostPath:
            type: Directory
            path: /etc/islab-k8s/backend/data
        - name: kube-config
          hostPath:
            type: File
            path: /etc/kubernetes/admin.conf
