apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: api-server-base-worker
  namespace: kube-system
  labels:
    app: api-server-base-worker
spec:
  selector:
    matchLabels:
      app: api-server-base-worker
  template:
    metadata:
      labels:
        app: api-server-base-worker
    spec:
      serviceAccountName: api-server-base
      hostPID: true
      containers:
        - name: api-server-base-worker
          image: yogawulala/k8s-api-server-worker:latest
          imagePullPolicy: Never #Always
          securityContext:
            privileged: true
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "2"
              memory: "1024M"
          command: ["/bin/bash"]
          args: ["-c", "/app/main"]
          env:
            - name: LISTEN_IP
              value: "0.0.0.0"
            - name: LISTEN_PORT
              value: "8080"
            - name: LOG_LEVEL
              value: "INFO"
          volumeMounts:
            - name: log-dir
              mountPath: /app/log
      volumes:
        - name: log-dir
          hostPath:
            type: DirectoryOrCreate
            path: /mnt/k8s-data/islab-backend/log
