name: islab-k8s CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  BASE_IMAGE_NAME: k8s-api-server
  DOCKERHUB_USER: yogawulala

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: build image
        run: | 
          cd backend
          ls
          docker build . -f docker/master/Dockerfile -t $DOCKERHUB_USER/$BASE_IMAGE_NAME-master
          docker build . -f docker/worker/Dockerfile -t $DOCKERHUB_USER/$BASE_IMAGE_NAME-worker

      - name: login to dockerhub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u $DOCKERHUB_USER --password-stdin

      - name: Push image
        run: |
          docker push $DOCKERHUB_USER/$BASE_IMAGE_NAME-master
          docker push $DOCKERHUB_USER/$BASE_IMAGE_NAME-worker
